### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by mz0005** [wvbe/node-eyetribe#1]
Hi, I am a new one to use websocket and npm. I have download the package and calibrate my eyetribe before launch but how to do npm install and npm start?

**Comment by wvbe** [comment]
Hey @mz0005, welcome to the world of NPM.  You'll need to install NodeJS, the latest version comes with NPM. I'm not an expert on Windows, but I think you can just use the installer from http://nodejs.org/download/.

After that, open a terminal in the directory where you downloaded this package and type "npm install". NPM should now install all packages required by this one.

When that's finished, make sure your EyeTribe is running and type "npm start" in the command line. If all is well it may take a few seconds for the server to catch onto EyeTribe, and after that (if I remember correctly) it'll dump a whole lot of data to your terminal. You can ignore this, instead, open the index.html file in your browser. It should now visualise what you're looking at in a heatmap :)

Good luck! I don't have my EyeTribe available anymore (it was a collegue's), so if you run into trouble I'll be happy to help but you may have to tweak it a little bit yourself too ;)

**Comment by mz0005** [comment]
That is very helpful. Problem fixed. Thank you!
It seems I need to hard code directory of socket.io in my code and run
"node server.js" before I open index.html.

Have a nice day,

-Mini

**Comment by wvbe** [comment]
Thanks! If you have any questions, feel free to ask :) That goes for anyone
