### ISSUE TITLE
Which Eye-tribe SDK?

### ISSUE THREAD

**Issue by njss** [wvbe/node-eyetribe#2]
Hi,

This is a great contribution. 
Can you tell me in which version of the eyetribe sdk is this project relying on?

Thank you!

best,
Nelson

**Comment by wvbe** [comment]
Hey njss, I'm sorry but I did not record the SDK version at the time. I also no longer have access to the EyeTribe equipment, so I can not retrieve this information for you. Sorry about that!

Regards,
Wybe

**Comment by njss** [comment]
No problem, I've tried and it worked well with the latest SDK version.
Thanks!

**Comment by wvbe** [comment]
Glad to hear, thanks for letting me/us know
